### ISSUE TITLE
When resetting is disabled a button should not display counter after being clicked

### ISSUE THREAD

**Issue by Adakar** [ProjectAJ14/timer_button#13]
If a user sets `resetTimerOnPressed: false,` the text displayed on the button after the click shows initial timeout value.
![obraz](https://user-images.githubusercontent.com/6673954/139127926-a39f41f5-cb5c-499d-8e35-2036718df2c3.png)

I find it a bit counter-intuitive. As the counting down is done, action/click is triggered, I'd expect to see the button being "disabled" but with no counter value. Just value of the `label` parameter. No pipeline, no counter value, no time units.

@ajaykumargithub2114 If you think it makes sense and you are fine with that please assign the issue to me. I'd be happy to implement proposed change :)

**Comment by ProjectAJ14** [comment]
Closed with timer_button: ^2.1.1
