### ISSUE TITLE
setState called after navigation

### ISSUE THREAD

**Issue by Priyanshu-Kashyap** [ProjectAJ14/timer_button#14]
```
E/flutter (25191): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: setState() called after dispose(): _TimerButtonState#5eb2e(lifecycle state: defunct, not mounted)
E/flutter (25191): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (25191): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (25191): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (25191): #0      State.setState.<anonymous closure>
package:flutter/…/widgets/framework.dart:1052
E/flutter (25191): #1      State.setState
package:flutter/…/widgets/framework.dart:1087
E/flutter (25191): #2      _TimerButtonState._timerUpdate.<anonymous closure>
package:timer_button/timer_button.dart:92
E/flutter (25191): #3      _TimerButtonState._timerUpdate.<anonymous closure>
package:timer_button/timer_button.dart:90
E/flutter (25191): #4      _rootRun (dart:async/zone.dart:1420:47)
E/flutter (25191): #5      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (25191): #6      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (25191): #7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (25191): #8      _rootRun (dart:async/zone.dart:1428:13)
E/flutter (25191): #9      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (25191): #10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
E/flutter (25191): #11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (25191): #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (25191): #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (25191): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
### this code is the reason of above log because setState was called even after i navigated to another page
```  
_timerUpdate() {
    Timer(const Duration(seconds: aSec), () async {
      setState(() {
        timeCounter--;
      });
      if (timeCounter != 0)
        _timerUpdate();
      else
        timeUpFlag = true;
    });
  }
```

### fixed
```
  _timerUpdate() {
    if (!mounted) return;
    Timer(const Duration(seconds: aSec), () async {
      setState(() {
        timeCounter--;
      });
      if (timeCounter != 0)
        _timerUpdate();
      else
        timeUpFlag = true;
    });
  }
```

shall i create a pull request

**Comment by chetanxpatil** [comment]
`library timer_button;

import 'dart:async';
import 'dart:ui';

import 'package:flutter/material.dart';

enum ButtonType {
  RaisedButton,
  FlatButton,
  OutlineButton,
  ElevatedButton,
  TextButton,
  OutlinedButton
}

const int aSec = 1;

const String _secPostFix = 's';
const String labelSplitter = " |  ";

class TimerButton extends StatefulWidget {
  /// Create a TimerButton button.
  ///
  /// The [label], [onPressed], and [timeOutInSeconds]
  /// arguments must not be null.

  ///label
  final String label;

  ///secPostFix
  final String secPostFix;

  ///[timeOutInSeconds] after which the button is enabled
  final int timeOutInSeconds;

  ///[onPressed] Called when the button is tapped or otherwise activated.
  final VoidCallback onPressed;

  /// Defines the button's base colors
  final Color color;

  /// The color to use for this button's background/border when the button is disabled.
  final Color disabledColor;

  /// activeTextStyle
  final TextStyle? activeTextStyle;

  ///disabledTextStyle
  final TextStyle disabledTextStyle;

  ///buttonType
  final ButtonType buttonType;

  ///If resetTimerOnPressed is true reset the timer when the button is pressed : default to true
  final bool resetTimerOnPressed;

  const TimerButton({
    Key? key,
    required this.label,
    required this.onPressed,
    required this.timeOutInSeconds,
    this.secPostFix = _secPostFix,
    this.color = Colors.blue,
    this.resetTimerOnPressed = true,
    this.disabledColor = Colors.grey,
    this.buttonType = ButtonType.RaisedButton,
    this.activeTextStyle,
    this.disabledTextStyle = const TextStyle(color: Colors.black45),
  }) : super(key: key);

  @override
  _TimerButtonState createState() => _TimerButtonState();
}

class _TimerButtonState extends State<TimerButton> {
  bool timeUpFlag = false;
  int timeCounter = 0;

  String get _timerText => '$timeCounter${widget.secPostFix}';

  late Timer ourTimer;


  @override
  void initState() {
    super.initState();
    timeCounter = widget.timeOutInSeconds;
    _timerUpdate();
  }

  _timerUpdate() {
    if (!mounted) return;
    ourTimer = Timer(const Duration(seconds: aSec), () async {
      setState(() {
        timeCounter--;
      });
      if (timeCounter != 0)
        _timerUpdate();
      else
        timeUpFlag = true;
    });
  }



  Widget _buildChild() {
    TextStyle? activeTextStyle;
    if (widget.activeTextStyle == null) {
      if (widget.buttonType == ButtonType.OutlinedButton ||
          widget.buttonType == ButtonType.OutlineButton) {
        activeTextStyle = TextStyle(color: widget.color);
      } else {
        activeTextStyle = TextStyle(color: Colors.white);
      }
    } else {
      activeTextStyle = widget.activeTextStyle;
    }
    return Container(
      child: timeUpFlag
          ? Text(
              widget.label,
              style: activeTextStyle,
            )
          : Text(
              widget.label + labelSplitter + _timerText,
              style: widget.disabledTextStyle,
            ),
    );
  }

  _onPressed() {
    if (timeUpFlag) {
      setState(() {
        timeUpFlag = false;
      });
      timeCounter = widget.timeOutInSeconds;

      widget.onPressed();

      // reset the timer when the button is pressed
      if (widget.resetTimerOnPressed) {
        _timerUpdate();
      }
    }
  }

 @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    ourTimer.cancel();
  }

  @override
  Widget build(BuildContext context) {
    switch (widget.buttonType) {
      //RaisedButton is deprecated, use ElevatedButton instead
      case ButtonType.RaisedButton:
        //TODO: (Ajay) Remove deprecated members
        // ignore: deprecated_member_use
        return RaisedButton(
          disabledColor: widget.disabledColor,
          color: timeUpFlag ? widget.color : widget.disabledColor,
          onPressed: _onPressed,
          child: _buildChild(),
        );
      //FlatButton is deprecated, use TextButton instead
      case ButtonType.FlatButton:
        // ignore: deprecated_member_use
        return FlatButton(
          color: timeUpFlag ? widget.color : widget.disabledColor,
          disabledColor: widget.disabledColor,
          onPressed: _onPressed,
          child: _buildChild(),
        );
      //OutlineButton is deprecated, use OutlinedButton instead
      case ButtonType.OutlineButton:
        // ignore: deprecated_member_use
        return OutlineButton(
          borderSide: BorderSide(
            color: timeUpFlag ? widget.color : widget.disabledColor,
          ),
          disabledBorderColor: widget.disabledColor,
          onPressed: _onPressed,
          child: _buildChild(),
        );
      case ButtonType.ElevatedButton:
        return ElevatedButton(
            onPressed: _onPressed,
            child: _buildChild(),
            style: ElevatedButton.styleFrom(
              primary: timeUpFlag ? widget.color : widget.disabledColor,
            ));
      case ButtonType.TextButton:
        return TextButton(
            onPressed: _onPressed,
            child: _buildChild(),
            style: TextButton.styleFrom(
              backgroundColor: timeUpFlag ? widget.color : widget.disabledColor,
            ));
      case ButtonType.OutlinedButton:
        return OutlinedButton(
            onPressed: _onPressed,
            child: _buildChild(),
            style: OutlinedButton.styleFrom(
              side: BorderSide(
                color: timeUpFlag ? widget.color : widget.disabledColor,
              ),
            ));
      default:
        return Container();
    }
  }
}
`

solved it can use this now

**Comment by chetanxpatil** [comment]
library timer_button;

import 'dart:async';
import 'dart:ui';

import 'package:flutter/material.dart';

enum ButtonType {
  RaisedButton,
  FlatButton,
  OutlineButton,
  ElevatedButton,
  TextButton,
  OutlinedButton
}

const int aSec = 1;

const String _secPostFix = 's';
const String labelSplitter = " |  ";

class TimerButton extends StatefulWidget {
  /// Create a TimerButton button.
  ///
  /// The [label], [onPressed], and [timeOutInSeconds]
  /// arguments must not be null.

  ///label
  final String label;

  ///secPostFix
  final String secPostFix;

  ///[timeOutInSeconds] after which the button is enabled
  final int timeOutInSeconds;

  ///[onPressed] Called when the button is tapped or otherwise activated.
  final VoidCallback onPressed;

  /// Defines the button's base colors
  final Color color;

  /// The color to use for this button's background/border when the button is disabled.
  final Color disabledColor;

  /// activeTextStyle
  final TextStyle? activeTextStyle;

  ///disabledTextStyle
  final TextStyle disabledTextStyle;

  ///buttonType
  final ButtonType buttonType;

  ///If resetTimerOnPressed is true reset the timer when the button is pressed : default to true
  final bool resetTimerOnPressed;

  const TimerButton({
    Key? key,
    required this.label,
    required this.onPressed,
    required this.timeOutInSeconds,
    this.secPostFix = _secPostFix,
    this.color = Colors.blue,
    this.resetTimerOnPressed = true,
    this.disabledColor = Colors.grey,
    this.buttonType = ButtonType.RaisedButton,
    this.activeTextStyle,
    this.disabledTextStyle = const TextStyle(color: Colors.black45),
  }) : super(key: key);

  @override
  _TimerButtonState createState() => _TimerButtonState();
}

class _TimerButtonState extends State<TimerButton> {
  bool timeUpFlag = false;
  int timeCounter = 0;

  String get _timerText => '$timeCounter${widget.secPostFix}';

  late Timer ourTimer;


  @override
  void initState() {
    super.initState();
    timeCounter = widget.timeOutInSeconds;
    _timerUpdate();
  }

  _timerUpdate() {
    if (!mounted) return;
    ourTimer = Timer(const Duration(seconds: aSec), () async {
      setState(() {
        timeCounter--;
      });
      if (timeCounter != 0)
        _timerUpdate();
      else
        timeUpFlag = true;
    });
  }



  Widget _buildChild() {
    TextStyle? activeTextStyle;
    if (widget.activeTextStyle == null) {
      if (widget.buttonType == ButtonType.OutlinedButton ||
          widget.buttonType == ButtonType.OutlineButton) {
        activeTextStyle = TextStyle(color: widget.color);
      } else {
        activeTextStyle = TextStyle(color: Colors.white);
      }
    } else {
      activeTextStyle = widget.activeTextStyle;
    }
    return Container(
      child: timeUpFlag
          ? Text(
              widget.label,
              style: activeTextStyle,
            )
          : Text(
              widget.label + labelSplitter + _timerText,
              style: widget.disabledTextStyle,
            ),
    );
  }

  _onPressed() {
    if (timeUpFlag) {
      setState(() {
        timeUpFlag = false;
      });
      timeCounter = widget.timeOutInSeconds;

      widget.onPressed();

      // reset the timer when the button is pressed
      if (widget.resetTimerOnPressed) {
        _timerUpdate();
      }
    }
  }

 @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    ourTimer.cancel();
  }

  @override
  Widget build(BuildContext context) {
    switch (widget.buttonType) {
      //RaisedButton is deprecated, use ElevatedButton instead
      case ButtonType.RaisedButton:
        //TODO: (Ajay) Remove deprecated members
        // ignore: deprecated_member_use
        return RaisedButton(
          disabledColor: widget.disabledColor,
          color: timeUpFlag ? widget.color : widget.disabledColor,
          onPressed: _onPressed,
          child: _buildChild(),
        );
      //FlatButton is deprecated, use TextButton instead
      case ButtonType.FlatButton:
        // ignore: deprecated_member_use
        return FlatButton(
          color: timeUpFlag ? widget.color : widget.disabledColor,
          disabledColor: widget.disabledColor,
          onPressed: _onPressed,
          child: _buildChild(),
        );
      //OutlineButton is deprecated, use OutlinedButton instead
      case ButtonType.OutlineButton:
        // ignore: deprecated_member_use
        return OutlineButton(
          borderSide: BorderSide(
            color: timeUpFlag ? widget.color : widget.disabledColor,
          ),
          disabledBorderColor: widget.disabledColor,
          onPressed: _onPressed,
          child: _buildChild(),
        );
      case ButtonType.ElevatedButton:
        return ElevatedButton(
            onPressed: _onPressed,
            child: _buildChild(),
            style: ElevatedButton.styleFrom(
              primary: timeUpFlag ? widget.color : widget.disabledColor,
            ));
      case ButtonType.TextButton:
        return TextButton(
            onPressed: _onPressed,
            child: _buildChild(),
            style: TextButton.styleFrom(
              backgroundColor: timeUpFlag ? widget.color : widget.disabledColor,
            ));
      case ButtonType.OutlinedButton:
        return OutlinedButton(
            onPressed: _onPressed,
            child: _buildChild(),
            style: OutlinedButton.styleFrom(
              side: BorderSide(
                color: timeUpFlag ? widget.color : widget.disabledColor,
              ),
            ));
      default:
        return Container();
    }
  }
}

**Comment by chetanxpatil** [comment]
```dart
library timer_button;

import 'dart:async';
import 'dart:ui';

import 'package:flutter/material.dart';

enum ButtonType {
  RaisedButton,
  FlatButton,
  OutlineButton,
  ElevatedButton,
  TextButton,
  OutlinedButton
}

const int aSec = 1;

const String _secPostFix = 's';
const String labelSplitter = " |  ";

class TimerButton extends StatefulWidget {
  /// Create a TimerButton button.
  ///
  /// The [label], [onPressed], and [timeOutInSeconds]
  /// arguments must not be null.

  ///label
  final String label;

  ///secPostFix
  final String secPostFix;

  ///[timeOutInSeconds] after which the button is enabled
  final int timeOutInSeconds;

  ///[onPressed] Called when the button is tapped or otherwise activated.
  final VoidCallback onPressed;

  /// Defines the button's base colors
  final Color color;

  /// The color to use for this button's background/border when the button is disabled.
  final Color disabledColor;

  /// activeTextStyle
  final TextStyle? activeTextStyle;

  ///disabledTextStyle
  final TextStyle disabledTextStyle;

  ///buttonType
  final ButtonType buttonType;

  ///If resetTimerOnPressed is true reset the timer when the button is pressed : default to true
  final bool resetTimerOnPressed;

  const TimerButton({
    Key? key,
    required this.label,
    required this.onPressed,
    required this.timeOutInSeconds,
    this.secPostFix = _secPostFix,
    this.color = Colors.blue,
    this.resetTimerOnPressed = true,
    this.disabledColor = Colors.grey,
    this.buttonType = ButtonType.RaisedButton,
    this.activeTextStyle,
    this.disabledTextStyle = const TextStyle(color: Colors.black45),
  }) : super(key: key);

  @override
  _TimerButtonState createState() => _TimerButtonState();
}

class _TimerButtonState extends State<TimerButton> {
  bool timeUpFlag = false;
  int timeCounter = 0;

  String get _timerText => '$timeCounter${widget.secPostFix}';

  late Timer ourTimer;


  @override
  void initState() {
    super.initState();
    timeCounter = widget.timeOutInSeconds;
    _timerUpdate();
  }

  _timerUpdate() {
    if (!mounted) return;
    ourTimer = Timer(const Duration(seconds: aSec), () async {
      setState(() {
        timeCounter--;
      });
      if (timeCounter != 0)
        _timerUpdate();
      else
        timeUpFlag = true;
    });
  }



  Widget _buildChild() {
    TextStyle? activeTextStyle;
    if (widget.activeTextStyle == null) {
      if (widget.buttonType == ButtonType.OutlinedButton ||
          widget.buttonType == ButtonType.OutlineButton) {
        activeTextStyle = TextStyle(color: widget.color);
      } else {
        activeTextStyle = TextStyle(color: Colors.white);
      }
    } else {
      activeTextStyle = widget.activeTextStyle;
    }
    return Container(
      child: timeUpFlag
          ? Text(
              widget.label,
              style: activeTextStyle,
            )
          : Text(
              widget.label + labelSplitter + _timerText,
              style: widget.disabledTextStyle,
            ),
    );
  }

  _onPressed() {
    if (timeUpFlag) {
      setState(() {
        timeUpFlag = false;
      });
      timeCounter = widget.timeOutInSeconds;

      widget.onPressed();

      // reset the timer when the button is pressed
      if (widget.resetTimerOnPressed) {
        _timerUpdate();
      }
    }
  }

 @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    ourTimer.cancel();
  }

  @override
  Widget build(BuildContext context) {
    switch (widget.buttonType) {
      //RaisedButton is deprecated, use ElevatedButton instead
      case ButtonType.RaisedButton:
        //TODO: (Ajay) Remove deprecated members
        // ignore: deprecated_member_use
        return RaisedButton(
          disabledColor: widget.disabledColor,
          color: timeUpFlag ? widget.color : widget.disabledColor,
          onPressed: _onPressed,
          child: _buildChild(),
        );
      //FlatButton is deprecated, use TextButton instead
      case ButtonType.FlatButton:
        // ignore: deprecated_member_use
        return FlatButton(
          color: timeUpFlag ? widget.color : widget.disabledColor,
          disabledColor: widget.disabledColor,
          onPressed: _onPressed,
          child: _buildChild(),
        );
      //OutlineButton is deprecated, use OutlinedButton instead
      case ButtonType.OutlineButton:
        // ignore: deprecated_member_use
        return OutlineButton(
          borderSide: BorderSide(
            color: timeUpFlag ? widget.color : widget.disabledColor,
          ),
          disabledBorderColor: widget.disabledColor,
          onPressed: _onPressed,
          child: _buildChild(),
        );
      case ButtonType.ElevatedButton:
        return ElevatedButton(
            onPressed: _onPressed,
            child: _buildChild(),
            style: ElevatedButton.styleFrom(
              primary: timeUpFlag ? widget.color : widget.disabledColor,
            ));
      case ButtonType.TextButton:
        return TextButton(
            onPressed: _onPressed,
            child: _buildChild(),
            style: TextButton.styleFrom(
              backgroundColor: timeUpFlag ? widget.color : widget.disabledColor,
            ));
      case ButtonType.OutlinedButton:
        return OutlinedButton(
            onPressed: _onPressed,
            child: _buildChild(),
            style: OutlinedButton.styleFrom(
              side: BorderSide(
                color: timeUpFlag ? widget.color : widget.disabledColor,
              ),
            ));
      default:
        return Container();
    }
  }
}
```

**Comment by chetanxpatil** [comment]
use this code i pasted just commit this it will solve your issue

**Comment by hyperov** [comment]
i had the same issue but i have another solution
just cancel the timer in onDispose

```
late Timer timer;

_timerUpdate() {
    timer = Timer(const Duration(seconds: aSec), () async {
      setState(() {
        timeCounter--;
      });
      if (timeCounter != 0)
        _timerUpdate();
      else
        timeUpFlag = true;
    });
  }

 dispose() {
    super.dispose();
    timer.cancel();
  }
```
