### ISSUE TITLE
Delete the outline button because its no longer supported in flutter 3.0.0

### ISSUE THREAD

**Issue by moneebshammout** [ProjectAJ14/timer_button#18]
just delete the lines from 164 to 174 and the package is ready to go

**Comment by haziqdzul** [comment]
Please remove the outline button. I cannot use timer_button package because of this bug

**Comment by tomyamGTX** [comment]
![IMG-20221109-WA0015](https://user-images.githubusercontent.com/74492300/200758157-15ab327e-ecc3-4162-b7a8-f07b3d37b480.jpg)

Raised button, outline button and flat button issue

**Comment by ProjectAJ14** [comment]
Closed with timer_button: ^2.1.1
